### ISSUE TITLE
MediumEditor global variable

### ISSUE THREAD

**Issue by agereaude** [yabwe/medium-editor-tables#14]
Since v0.4.0, MediumEditor is needed as a global variable. I'm instanciating the editor inside another object, making the variable local to that object and unavailable globally.
Shouldn't MediumEditor be imported from its peer dependency so as not to depend from global variables?

``` javascript
import MediumEditor from 'medium-editor';
// OR
var MediumEditor = require('medium-editor');
```

**Comment by ebengtso** [comment]
I was about to ask the same feature, so MediumEditor should support require?

I'm able to use it with dojo, but I'm having a problem to load extensions because they rely on global variable

**Comment by j0k3r** [comment]
This issue was moved to yabwe/medium-editor#773

**Comment by armetiz** [comment]
Hi there.

JFYI,
I'm still not able to use this plugin within a standard CommonJS project.

> MediumEditor is not defined

Regards.

**Comment by kevincobain2000** [comment]
Although this is closed, but for a standard project, just it still doesn't work.
Following work around has worked

```
window.MediumEditor = require('../../../node_modules/medium-editor/dist/js/medium-editor.js');
window.MediumEditorTable = require('../../../node_modules/medium-editor-tables/dist/js/medium-editor-tables.js');
// other imports as usual

import rangy from 'rangy';
import rangyHighlight from 'rangy/lib/rangy-highlighter';
import rangyClassApplier from 'rangy/lib/rangy-classapplier';
```

Next you should be able to use ``MediumEditorTable`` under extensions.
