### ISSUE TITLE
Does not work with Medium-Editor 5.5.4

### ISSUE THREAD

**Issue by websirnik** [yabwe/medium-editor-tables#15]
I've just tries the demo with the current latest Medium-Editor 5.5.4. It does not work as expected. Table gets initialised, but all the `<td></td>` are empty, there is no `<br>` tag like before, as the result it's barely usable.

**Comment by j0k3r** [comment]
This is related to this change: yabwe/medium-editor#746
I'll submit a fix to medium-editor soon.

**Comment by j0k3r** [comment]
As of [medium-editor 5.6.2](https://github.com/yabwe/medium-editor/releases/tag/5.6.2), this should be fixed. I've also updated the demo page.

Thanks for the report !
