### ISSUE TITLE
AMD issues and fix

### ISSUE THREAD

**Issue by spacegangster** [yabwe/medium-editor-tables#21]
Hello. The plugin doesn't load when I use it with RequireJS. Dependent module receives undefined instead of plugin constructor.
To fix it, the plugin function should be defined through defining function.

``` javascript
} else if (typeof define === 'function' && define.amd) {
  // define(factory); - RequireJS will think that factory defines something
  define(function () { return factory}); // instead we use a wrapper, that will return our factory.
```

This works and tested. You can see the same approach in Medium-Editor itself.
https://github.com/yabwe/medium-editor/blob/master/dist/js/medium-editor.js#L391

**Comment by daviferreira** [comment]
Can you open a PR? :)

**Comment by spacegangster** [comment]
Sure. https://github.com/yabwe/medium-editor-tables/pull/22

**Comment by daviferreira** [comment]
:+1:
