### ISSUE TITLE
Setting custom rows/columns number breaks grid selector

### ISSUE THREAD

**Issue by micred** [yabwe/medium-editor-tables#23]
I've setup with success:
- medium-editor 5.14.2 
- medium-editor-tables 0.5.0.

It works good with MediumEditorTable default settings (rows: 10, columns: 10), but it breaks when I initialize MediumEditorTable with custom rows/column number.

Here an example with:
1. rows: 10, column: 2
2.  rows: 10, column: 4

![issuetables](https://cloud.githubusercontent.com/assets/511434/13171155/89712936-d6f1-11e5-9835-b1dafe44f38d.jpg)

I also tried without success with medium-editor 5.5.1.

**Comment by linkesch** [comment]
I'm working on a fix. Thank you for reporting this.

**Comment by micred** [comment]
Great, thank you!

**Comment by linkesch** [comment]
Version [0.5.1](https://github.com/yabwe/medium-editor-tables/releases/tag/0.5.1) containing the fix was just released. Let me know if it works for you.
