### ISSUE TITLE
Extension not working with latest Medium Editor version (5.15.0)

### ISSUE THREAD

**Issue by peca11** [yabwe/medium-editor-tables#25]
Hi, 
I think the table extension isn't working with the latest MediumEditor version (5.15.0)

This is what I did to test it out:
1 - Downloaded the latest version of ME and Table extension.
2 - On the ME folder opened the example custom-toolbar.html, added the toolbar extension, js and css, defined the toolbar and extension.
3 - Opened the html on the browser, the table button appears in the toolbar, when I click on it nothing happens.

I then tried the same html with the ME v5.6.2, that is being used on the demo (http://yabwe.github.io/medium-editor-tables/) and it works fine.

Just a small detail, there is a console.log on line 283, I think it was left by mistake. 

Thanks

**Comment by linkesch** [comment]
I'm working on a fix. Thanks for reporting this.

**Comment by linkesch** [comment]
Version [0.5.1](https://github.com/yabwe/medium-editor-tables/releases/tag/0.5.1) containing the fix was just released. Let me know if it works for you.

**Comment by peca11** [comment]
Thanks @orthes 
I've just tested the new version. It's working great!
