### ISSUE TITLE
How to override 'contentDefault'

### ISSUE THREAD

**Issue by abijr** [yabwe/medium-editor-tables#28]
How do I override the 'contentDefault' property? I want to customize the content of the button.

**Comment by n457** [comment]
Hello mate,
You have to specify the options like this :

``` javascript
var editor = new MediumEditor(editableBlock, {
  extensions: {
    table: new MediumEditorTable({
      classList: ['my-class1', 'my-class2'],
      contentDefault: 'whateveeerrr',
      aria: false
      // etc....
    })
  }
});
```

The available options are the same as the MediumEditor itself. See here : https://github.com/yabwe/medium-editor#button-options

**Comment by abijr** [comment]
Thanks!
