### ISSUE TITLE
Editor breaks in electron environment 

### ISSUE THREAD

**Issue by sajus** [yabwe/medium-editor-tables#29]
https://github.com/yabwe/medium-editor-tables/blob/master/src/wrappers/start.js#L3

In electron environment, which use Nodejs, module is defined and editor tries to export itself. Which causes breaks to already exist electron code base.

Exactly the same issue with: https://github.com/yabwe/medium-editor/issues/1123

**Comment by durgeshahire4** [comment]
https://github.com/durgeshahire4/medium-editor-tables/commit/fc7ce57e3920df758d012cdc6d0e9512e59720aa

**Comment by durgeshahire4** [comment]
PR: https://github.com/yabwe/medium-editor-tables/pull/30
