### ISSUE TITLE
Table getting inserted inside <p> tag

### ISSUE THREAD

**Issue by sajus** [yabwe/medium-editor-tables#33]
Recently when I was editing my editor, i inserted couple of text and ordered list and when i tried to insert the table. It just rendered `<table>` tag inside the `<p>` tag and reset of the `<tbody>` outside the `<p>` tag. 

There should be conditional check for the parent node, where table is getting inserted, is not any block elements which doesn't support any other block level elements such as `<p>` tag.

**Comment by sajus** [comment]
@j0k3r , do we have any inputs in this issue?

**Comment by j0k3r** [comment]
@sajus Sorry I haven't. But if you find the problem and fix it I'll be happy to merge the PR

**Comment by sajus** [comment]
@j0k3r  I've created PR which resolves this issue, can you please take a look into this. https://github.com/yabwe/medium-editor-tables/pull/36
