### ISSUE TITLE
Internal tabbing is not working.

### ISSUE THREAD

**Issue by pkatta** [yabwe/medium-editor-tables#47]
Internal tabbing is not working in the table.
Getting below error when I press the tab button inside the table.

![screen shot 2017-05-29 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/8381689/26542533/ec059948-4477-11e7-9745-a5ef1f0b6833.png)

**Comment by pkatta** [comment]
@j0k3r : Please check once.

**Comment by j0k3r** [comment]
Yep looks like a real bug.
I've no time to fix it. Feel free to subit a PR to fix it
