### ISSUE TITLE
Create Rows and Columns After the Fact

### ISSUE THREAD

**Issue by debugd** [yabwe/medium-editor-tables#59]
Is there a way to add rows + columns after the table has already been created?

**Comment by stefanpejcic** [comment]
You can make a table, say 2x2, and then add extra rows or tables by selecting the table again and clicking the table button, then adding as many rows/columns as you want.


test in the demo: http://yabwe.github.io/medium-editor-tables/

<img src="https://i.imgur.com/Yu9UBZ4.png">
