### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by daviferreira** [yabwe/medium-editor-tables#8]
- add row above
- add row below
- delete row
- add column before
- add column after
- delete column

**Comment by anatoliyarkhipov** [comment]
Is there way now to add or delete a row without context menu?

**Comment by daviferreira** [comment]
If you select and backspace/delete it might work sometimes :P

**Comment by anatoliyarkhipov** [comment]
Just tried this and can't say that it works very well :) 
Should I create a new issue for adding/removing without context menu?

**Comment by daviferreira** [comment]
Sure, and if you could add a possible UI idea for that action, I'm not sure which one would be good :)

**Comment by anatoliyarkhipov** [comment]
I'm not sure, but maybe this is good enough for a temporary solution. A row can be removed when user presses backspace in the first cell and cursor stays before the first symbol. And we can show the confirmation dialog to prevent accidental deleting.

![screenshot_2](https://cloud.githubusercontent.com/assets/1934180/7937465/3a229fea-0951-11e5-9faf-c6036fe030b3.png)

**Comment by agereaude** [comment]
Maybe this should be done with the toolbar button instead of a context menu. I've been trying to add this functionality, but I'm not entirely sure about how everything works. The idea is to change to content of the div.medium-editor-table-builder if the cursor is inside a cell:

``` javascript
show: function () {
        this.setActive();

        var range = MediumEditor.selection.getSelectionRange(this.document);
        if (range.startContainer.nodeName.toLowerCase() === 'td' ||
          range.endContainer.nodeName.toLowerCase() === 'td' ||
          MediumEditor.util.getClosestTag(MediumEditor.selection.getSelectedParentElement(range), 'td')) {
            this.builder.setEditor();
        } else {
            this.builder.setBuilder();
        }
        this.builder.show(this.button.offsetLeft);
        var elements = this.document.getElementsByClassName('medium-editor-table-builder-grid');
        for (var i = 0; i < elements.length; i++) {
            // TODO: what is 16 and what is 2?
            elements[i].style.height = (16 * this.rows + 2) + 'px';
            elements[i].style.width = (16 * this.columns + 2) + 'px';
        }
    },
```

Then, the builder should implement the setEditor, setBuilder methods to change from one to the other. This is where I'm stuck. I can't figure out how it works:

``` javascript
setEditor: function() {
        this._builder = this._root;

        this._root = this._doc.createElement('div');
        this._root.className = 'medium-editor-table-builder';
        this._root.innerHTML = "<button>Add row</button>"; // this is not happening

        console.log(this._root);
    },

setBuilder: function() {
        this._root = this._builder;
    }
```

With this working and the ability to get the node where the cursor is placed, it should be relatively easy to add and delete rows and columns relative to it.
